dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
sudo: false
install:
  - pip install --upgrade pip
  - pip --version
  - pip install tox-travis coveralls
script:
  - tox -v
after_success:
  - cd tests && coveralls
